export interface TarotCard {
  id: number;
  name: string;
  nameEn: string;
  suit?: string;
  number?: number;
  upright: string[];
  reversed: string[];
  keywords: string[];
  imageUrl: string;
}

export const RIDER_WAITE_DECK: TarotCard[] = [
  // Major Arcana
  {
    id: 0,
    name: "The Fool",
    nameEn: "The Fool",
    upright: ["New beginnings", "Innocence", "Spontaneity", "Free spirit"],
    reversed: ["Recklessness", "Unnecessary risk", "Foolishness"],
    keywords: ["beginnings", "freedom", "adventure"],
    imageUrl: "/cards/rider-waite/00-fool.jpg",
  },
  {
    id: 1,
    name: "The Magician",
    nameEn: "The Magician",
    upright: ["Manifestation", "Power", "Action", "Focus"],
    reversed: ["Manipulation", "Wasted talent", "Illusion"],
    keywords: ["power", "action", "creation"],
    imageUrl: "/cards/rider-waite/01-magician.jpg",
  },
  {
    id: 2,
    name: "The High Priestess",
    nameEn: "The High Priestess",
    upright: ["Intuition", "Mystery", "Inner wisdom", "Subconscious"],
    reversed: ["Secrets", "Disconnection from intuition", "Repression"],
    keywords: ["intuition", "mystery", "wisdom"],
    imageUrl: "/cards/rider-waite/02-high-priestess.jpg",
  },
  {
    id: 3,
    name: "The Empress",
    nameEn: "The Empress",
    upright: ["Femininity", "Abundance", "Nature", "Nurturing"],
    reversed: ["Dependence", "Smothering", "Creative block"],
    keywords: ["abundance", "nature", "fertility"],
    imageUrl: "/cards/rider-waite/03-empress.jpg",
  },
  {
    id: 4,
    name: "The Emperor",
    nameEn: "The Emperor",
    upright: ["Authority", "Structure", "Control", "Fatherhood"],
    reversed: ["Tyranny", "Rigidity", "Domination"],
    keywords: ["authority", "structure", "leadership"],
    imageUrl: "/cards/rider-waite/04-emperor.jpg",
  },
  {
    id: 5,
    name: "The Hierophant",
    nameEn: "The Hierophant",
    upright: ["Tradition", "Conformity", "Morality", "Ethics"],
    reversed: ["Rebellion", "Subversion", "New methods"],
    keywords: ["tradition", "wisdom", "education"],
    imageUrl: "/cards/rider-waite/05-hierophant.jpg",
  },
  {
    id: 6,
    name: "The Lovers",
    nameEn: "The Lovers",
    upright: ["Love", "Harmony", "Relationships", "Choices"],
    reversed: ["Disharmony", "Imbalance", "Conflict of values"],
    keywords: ["love", "union", "choices"],
    imageUrl: "/cards/rider-waite/06-lovers.jpg",
  },
  {
    id: 7,
    name: "The Chariot",
    nameEn: "The Chariot",
    upright: ["Control", "Willpower", "Victory", "Determination"],
    reversed: ["Lack of control", "Aggression", "Defeat"],
    keywords: ["victory", "determination", "control"],
    imageUrl: "/cards/rider-waite/07-chariot.jpg",
  },
  {
    id: 8,
    name: "Strength",
    nameEn: "Strength",
    upright: ["Courage", "Patience", "Control", "Compassion"],
    reversed: ["Weakness", "Self-doubt", "Lack of discipline"],
    keywords: ["courage", "patience", "compassion"],
    imageUrl: "/cards/rider-waite/08-strength.jpg",
  },
  {
    id: 9,
    name: "The Hermit",
    nameEn: "The Hermit",
    upright: ["Introspection", "Inner search", "Guidance", "Solitude"],
    reversed: ["Isolation", "Forced loneliness", "Excessive withdrawal"],
    keywords: ["introspection", "wisdom", "search"],
    imageUrl: "/cards/rider-waite/09-hermit.jpg",
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    nameEn: "Wheel of Fortune",
    upright: ["Change", "Cycles", "Destiny", "Turning point"],
    reversed: ["Bad luck", "Resistance to change", "Negative cycle"],
    keywords: ["change", "destiny", "cycles"],
    imageUrl: "/cards/rider-waite/10-wheel.jpg",
  },
  {
    id: 11,
    name: "Justice",
    nameEn: "Justice",
    upright: ["Justice", "Fairness", "Truth", "Law"],
    reversed: ["Injustice", "Dishonesty", "Lack of accountability"],
    keywords: ["justice", "truth", "balance"],
    imageUrl: "/cards/rider-waite/11-justice.jpg",
  },
  {
    id: 12,
    name: "The Hanged Man",
    nameEn: "The Hanged Man",
    upright: ["Suspension", "Sacrifice", "New perspective", "Waiting"],
    reversed: ["Stagnation", "Resistance", "Delays"],
    keywords: ["sacrifice", "pause", "perspective"],
    imageUrl: "/cards/rider-waite/12-hanged.jpg",
  },
  {
    id: 13,
    name: "Death",
    nameEn: "Death",
    upright: ["Ending", "Transformation", "Transition", "Rebirth"],
    reversed: ["Resistance to change", "Stagnation", "Difficult ending"],
    keywords: ["transformation", "ending", "renewal"],
    imageUrl: "/cards/rider-waite/13-death.jpg",
  },
  {
    id: 14,
    name: "Temperance",
    nameEn: "Temperance",
    upright: ["Balance", "Moderation", "Patience", "Purpose"],
    reversed: ["Imbalance", "Excess", "Lack of harmony"],
    keywords: ["balance", "moderation", "harmony"],
    imageUrl: "/cards/rider-waite/14-temperance.jpg",
  },
  {
    id: 15,
    name: "The Devil",
    nameEn: "The Devil",
    upright: ["Bondage", "Materialism", "Addiction", "Dependence"],
    reversed: ["Liberation", "Detachment", "Breaking free"],
    keywords: ["addiction", "materialism", "bondage"],
    imageUrl: "/cards/rider-waite/15-devil.jpg",
  },
  {
    id: 16,
    name: "The Tower",
    nameEn: "The Tower",
    upright: ["Sudden change", "Revelation", "Chaos", "Destruction"],
    reversed: ["Avoiding disaster", "Fear of change", "Catharsis"],
    keywords: ["change", "revelation", "upheaval"],
    imageUrl: "/cards/rider-waite/16-tower.jpg",
  },
  {
    id: 17,
    name: "The Star",
    nameEn: "The Star",
    upright: ["Hope", "Faith", "Renewal", "Inspiration"],
    reversed: ["Hopelessness", "Discouragement", "Lack of faith"],
    keywords: ["hope", "inspiration", "serenity"],
    imageUrl: "/cards/rider-waite/17-star.jpg",
  },
  {
    id: 18,
    name: "The Moon",
    nameEn: "The Moon",
    upright: ["Illusion", "Fear", "Anxiety", "Subconscious"],
    reversed: ["Release of fear", "Revealed truth", "Clarity"],
    keywords: ["illusion", "intuition", "mystery"],
    imageUrl: "/cards/rider-waite/18-moon.jpg",
  },
  {
    id: 19,
    name: "The Sun",
    nameEn: "The Sun",
    upright: ["Success", "Joy", "Vitality", "Confidence"],
    reversed: ["Excessive optimism", "Depression", "Sadness"],
    keywords: ["success", "joy", "vitality"],
    imageUrl: "/cards/rider-waite/19-sun.jpg",
  },
  {
    id: 20,
    name: "Judgement",
    nameEn: "Judgement",
    upright: ["Judgement", "Rebirth", "Awakening", "Decision"],
    reversed: ["Self-doubt", "Unfair judgement", "Lack of forgiveness"],
    keywords: ["judgement", "renewal", "decision"],
    imageUrl: "/cards/rider-waite/20-judgement.jpg",
  },
  {
    id: 21,
    name: "The World",
    nameEn: "The World",
    upright: ["Completion", "Achievement", "Travel", "Wholeness"],
    reversed: ["Incompleteness", "Lack of closure", "Seeking"],
    keywords: ["completion", "achievement", "success"],
    imageUrl: "/cards/rider-waite/21-world.jpg",
  },
];

export const EGYPTIAN_DECK: TarotCard[] = [
  {
    id: 1,
    name: "The Magician",
    nameEn: "Le Bateleur - El Mago",
    upright: ["Manifestation", "Personal power", "Initiative", "Creativity"],
    reversed: ["Manipulation", "Illusion", "Lack of action"],
    keywords: ["power", "manifestation", "action"],
    imageUrl:
      "https://2.bp.blogspot.com/-iaBqerZTpps/WSzL2rWHOeI/AAAAAAAAE18/peVFholDD9kz0mJdxUC632-NNGP_LLWPgCLcB/s1600/1.jpg",
  },
  {
    id: 2,
    name: "The High Priestess",
    nameEn: "La Papesse - La Sacerdotisa",
    upright: ["Intuition", "Mystery", "Hidden wisdom", "Subconscious"],
    reversed: [
      "Revealed secrets",
      "Spiritual disconnection",
      "Lack of intuition",
    ],
    keywords: ["intuition", "mystery", "hidden knowledge"],
    imageUrl:
      "https://3.bp.blogspot.com/-XlDgx5ZEEDw/WTB2BrDZQsI/AAAAAAAABC4/IiNc812ZZ-kwbfXI13OL0VIkuB6ekN5TwCLcB/s1600/2.jpg",
  },
  {
    id: 3,
    name: "The Empress",
    nameEn: "L´Impératrice - La Emperatriz",
    upright: ["Abundance", "Nature", "Fertility", "Nurturing"],
    reversed: ["Dependence", "Creative block", "Lack of progress"],
    keywords: ["abundance", "motherhood", "creation"],
    imageUrl:
      "https://1.bp.blogspot.com/-H-m3ld9xOOM/WTHanN-T1wI/AAAAAAAAE4c/4WaHtdyIYgcFd0_9Zt22KkxzLGVDjWSaACLcB/s1600/3.jpg",
  },
  {
    id: 4,
    name: "The Emperor",
    nameEn: "L´Empereur - El Emperador",
    upright: ["Authority", "Structure", "Control", "Stability"],
    reversed: ["Tyranny", "Rigidity", "Excessive domination"],
    keywords: ["authority", "leadership", "structure"],
    imageUrl:
      "https://3.bp.blogspot.com/-5BQ9ruertEc/WTMzlK4ndpI/AAAAAAAAE5c/45qszfk5de0CwlWll0zct2S3WxY_HgyXwCLcB/s1600/4.jpg",
  },
  {
    id: 5,
    name: "The Hierophant",
    nameEn: "Le Pape - El Sumo Sacerdote",
    upright: [
      "Tradition",
      "Knowledge",
      "Spiritual guidance",
      "Conformity",
    ],
    reversed: ["Rebellion", "Dogma", "Spiritual rigidity"],
    keywords: ["tradition", "wisdom", "guidance"],
    imageUrl:
      "https://1.bp.blogspot.com/-CY1u8sm7dQE/WTNzziZeTyI/AAAAAAAABDM/tcxhPA_R74wODzQlptuY6g8s7Qi4vNwFgCLcB/s1600/5.jpg",
  },
  {
    id: 6,
    name: "The Lovers",
    nameEn: "L´Amoureux - El Enamorado",
    upright: ["Love", "Choices", "Union", "Harmony"],
    reversed: ["Imbalance", "Disharmony", "Poor choice"],
    keywords: ["love", "union", "decision"],
    imageUrl:
      "https://2.bp.blogspot.com/-XCuJQx8gyUg/WTRs-tdYM4I/AAAAAAAABEU/EED3PD-UN84F0KcxkG7nHd1w5CuJcwxDwCLcB/s1600/6.jpg",
  },
  {
    id: 7,
    name: "The Chariot",
    nameEn: "Le Chariot - El Caballero",
    upright: ["Victory", "Determination", "Control", "Willpower"],
    reversed: ["Lack of direction", "Aggression", "Defeat"],
    keywords: ["victory", "determination", "progress"],
    imageUrl:
      "https://4.bp.blogspot.com/-pWWrB4xMihs/WTR9HXa_1XI/AAAAAAAABFw/BOMKLflHtN8QQOYW_DswN_1fyUkNt9oAgCLcB/s1600/7.jpg",
  },
  {
    id: 8,
    name: "Justice",
    nameEn: "La Justice - La Justicia",
    upright: ["Justice", "Truth", "Balance", "Law"],
    reversed: ["Injustice", "Dishonesty", "Lack of accountability"],
    keywords: ["justice", "truth", "balance"],
    imageUrl:
      "https://4.bp.blogspot.com/-DBMu2ZA6J6I/WTW5C_4Ep9I/AAAAAAAABHc/0E342GIFouMO9Moej7CwoHiIwxAFAcOdACLcB/s1600/8.jpg",
  },
  {
    id: 9,
    name: "The Hermit",
    nameEn: "L´Hermite - El Ermitaño",
    upright: ["Introspection", "Wisdom", "Inner search", "Solitude"],
    reversed: ["Isolation", "Paranoia", "Excessive seclusion"],
    keywords: ["wisdom", "solitude", "introspection"],
    imageUrl:
      "https://2.bp.blogspot.com/-gNme-Bd_2b4/WTXnbPJ1OiI/AAAAAAAABJA/xyd9OwT0rVIdQgEIbnTs0RNjnYzvELZ2QCLcB/s1600/9.jpg",
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    nameEn: "La Roue de Fortune - La Rueda de la Fortuna",
    upright: ["Destiny", "Change", "Cycles", "Luck"],
    reversed: ["Bad luck", "Resistance to change", "Negative cycle"],
    keywords: ["destiny", "change", "cycles"],
    imageUrl:
      "https://1.bp.blogspot.com/-PF2eY_pjPY8/WTYIo77qDHI/AAAAAAAABKY/nWXH2r1M1X4tUCk0sKmke4SZiFHHHkqZACLcB/s1600/10.jpg",
  },
  {
    id: 11,
    name: "Strength",
    nameEn: "La Force - La Fuerza",
    upright: ["Strength", "Courage", "Patience", "Compassion"],
    reversed: ["Weakness", "Self-doubt", "Lack of discipline"],
    keywords: ["courage", "inner strength", "compassion"],
    imageUrl:
      "https://3.bp.blogspot.com/-vI163D-siik/WTcTgstZgZI/AAAAAAAABL4/TXGcb9WfiVcW5Cfm94OJ8ocDp7VJpTVpwCLcB/s1600/11.jpg",
  },
  {
    id: 12,
    name: "The Hanged Man",
    nameEn: "Le Pendu - El Colgado",
    upright: ["Suspension", "New perspective", "Sacrifice", "Waiting"],
    reversed: ["Stagnation", "Resistance", "Indecision"],
    keywords: ["sacrifice", "perspective", "pause"],
    imageUrl:
      "https://1.bp.blogspot.com/-_ootOZLdl6I/WTckXo7k1qI/AAAAAAAABNQ/J2lEkZdabto5_ZPhDdR4q2I7DOCMetbHQCLcB/s1600/12.jpg",
  },
  {
    id: 13,
    name: "Death",
    nameEn: "L´Arcane sans nom - El Arcano sin nombre",
    upright: ["Ending", "Transformation", "Transition", "Rebirth"],
    reversed: ["Resistance to change", "Stagnation", "Fear"],
    keywords: ["transformation", "ending", "rebirth"],
    imageUrl:
      "https://2.bp.blogspot.com/-F92LRfD55fI/WTc0Da-fASI/AAAAAAAABOk/p0DhX3x1LocQUOWd58EEiTlUvqreA3KIACLcB/s1600/13.jpg",
  },
  {
    id: 14,
    name: "Temperance",
    nameEn: "Tempérance - La Templanza",
    upright: ["Balance", "Moderation", "Patience", "Harmony"],
    reversed: ["Imbalance", "Excess", "Impatience"],
    keywords: ["balance", "moderation", "harmony"],
    imageUrl:
      "https://3.bp.blogspot.com/-WBHIIoA_DWU/WTdYHk9sGXI/AAAAAAAABQA/3jffw6NhyEkQ7gzW5GrxwW63-yvcg9OkACLcB/s1600/14.jpg",
  },
  {
    id: 15,
    name: "The Devil",
    nameEn: "Le Diable - El Diablo",
    upright: ["Materialism", "Addiction", "Bondage", "Temptation"],
    reversed: ["Liberation", "Detachment", "Overcoming"],
    keywords: ["addiction", "materialism", "bondage"],
    imageUrl:
      "https://4.bp.blogspot.com/-zbHDOphnLxY/WTduYyAbibI/AAAAAAAABRk/MbyP_09E3XkYgiFjdwhS1NBqm3kRWg-BwCLcB/s1600/15.jpg",
  },
  {
    id: 16,
    name: "The Tower",
    nameEn: "La Maison Dieu - La Casa de Dios",
    upright: ["Destruction", "Sudden change", "Revelation", "Liberation"],
    reversed: ["Avoiding disaster", "Fear of change", "Postponement"],
    keywords: ["upheaval", "revelation", "change"],
    imageUrl:
      "https://4.bp.blogspot.com/-3noIkCkmswg/WTh2Xlpm21I/AAAAAAAABTE/ZE7TndotpRUAdneTDPArchLmGq8xhLOxgCLcB/s1600/16.jpg",
  },
  {
    id: 17,
    name: "The Star",
    nameEn: "L´Étoile - La Estrella",
    upright: ["Hope", "Faith", "Inspiration", "Renewal"],
    reversed: ["Hopelessness", "Lack of faith", "Discouragement"],
    keywords: ["hope", "inspiration", "serenity"],
    imageUrl:
      "https://2.bp.blogspot.com/--zr0lAM0_jA/WTitW45K3RI/AAAAAAAABTo/3F26O8ew3vEXFzT57ZQhg1NtE3V0AWgOQCEw/s1600/17.jpg",
  },
  {
    id: 18,
    name: "The Moon",
    nameEn: "La Lune - La Luna",
    upright: ["Illusion", "Fear", "Anxiety", "Mystery"],
    reversed: ["Clarity", "Overcoming fears", "Revealed truth"],
    keywords: ["illusion", "intuition", "mystery"],
    imageUrl:
      "https://2.bp.blogspot.com/-Q9YnGHulIbY/WTnBCkjeHdI/AAAAAAAABV0/akWV1ppX_DANW1HDQToBOMSPyMrdvoCuACEw/s1600/18.jpg",
  },
  {
    id: 19,
    name: "The Sun",
    nameEn: "Le Soleil - El Sol",
    upright: ["Success", "Joy", "Vitality", "Positivity"],
    reversed: ["Excessive optimism", "Depression", "Lack of enthusiasm"],
    keywords: ["success", "joy", "vitality"],
    imageUrl:
      "https://1.bp.blogspot.com/-tQQV04ZINs4/WTnQUZ6dHRI/AAAAAAAABXc/cTrXSsa7Vm0UbPoCEj71vh5UyW4N6mrKgCLcB/s1600/19.jpg",
  },
  {
    id: 20,
    name: "Judgement",
    nameEn: "Le Jugement - El Juicio",
    upright: ["Judgement", "Rebirth", "Forgiveness", "Calling"],
    reversed: ["Self-judgement", "Doubt", "Lack of forgiveness"],
    keywords: ["judgement", "renewal", "calling"],
    imageUrl:
      "https://2.bp.blogspot.com/-vbBUgjCSKjo/WTnvuWRKQFI/AAAAAAAABXw/_fDRf0F7bdo4TfBDrijqlCOUyvvTl3B5wCLcB/s1600/20.jpg",
  },
  {
    id: 21,
    name: "The World",
    nameEn: "Le Monde - El Mundo",
    upright: ["Completion", "Achievement", "Travel", "Success"],
    reversed: ["Incompleteness", "Lack of closure", "Delays"],
    keywords: ["completion", "achievement", "wholeness"],
    imageUrl:
      "https://4.bp.blogspot.com/-F8_mRBZ57Qk/WToM4yunK8I/AAAAAAAABZQ/fbJ3zu2_tHI3e5jeasZ67lLT1Gho-UCxwCLcB/s1600/21.jpg",
  },
  {
    id: 22,
    name: "The Fool",
    nameEn: "Le Mat - El Loco",
    upright: ["New beginnings", "Innocence", "Freedom", "Adventure"],
    reversed: ["Recklessness", "Foolishness", "Unnecessary risk"],
    keywords: ["beginnings", "freedom", "spontaneity"],
    imageUrl:
      "https://4.bp.blogspot.com/-cNXKdHVFdGU/WTs80n3mNLI/AAAAAAAABag/qjjt7YMluF8OekvzrtTgvET-5_-Twev7QCLcB/s1600/22.jpg",
  },
];

export const SPREAD_TYPES = {
  SINGLE: {
    name: "Single Card",
    positions: ["Present"],
  },
  THREE_CARD: {
    name: "Three Cards",
    positions: ["Past", "Present", "Future"],
  },
  CELTIC_CROSS: {
    name: "Celtic Cross",
    positions: [
      "Present Situation",
      "Challenge",
      "Past",
      "Near Future",
      "Above (Goal)",
      "Below (Foundation)",
      "Advice",
      "External Influences",
      "Hopes and Fears",
      "Final Outcome",
    ],
  },
};
